export const cashierClientScript = String.raw`
const state={products:[],context:{ticketLots:[],servicePoints:[],voucherCodes:[]},cart:new Map(),method:'cash',servicePointId:null,online:false,operator:null,eventStream:null,sessionStream:null,generation:0,streamGeneration:0,reconnectTimer:null,view:'sales',noticeTimer:null,pendingCombo:null};
const $=id=>document.getElementById(id);
const money=c=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(c/100);
const uuid=()=>crypto.randomUUID();
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const permissions=()=>state.operator?.permissions||{sales:false,inventory:false,tickets:false,expenses:false,vouchers:false};
const enabled=key=>permissions()[key]===true;
function syncChromeHeight(){const chrome=document.querySelector('.app-chrome');if(chrome)document.documentElement.style.setProperty('--chrome-h',Math.ceil(chrome.getBoundingClientRect().height)+'px')}
function online(ok,text){state.online=ok;$('status').className='status '+(ok?'online':'');$('status').lastElementChild.textContent=text;draw()}
function amount(){return [...state.cart.values()].reduce((total,item)=>total+item.quantity*item.unitPriceCents,0)}
function count(){return [...state.cart.values()].reduce((total,item)=>total+item.quantity,0)}
function parseMoney(value){const amount=Number(String(value).trim().replace(',','.'));return Number.isFinite(amount)?Math.round(amount*100):0}
function paymentOptions(){return '<option value="pix">PIX</option><option value="cash">Dinheiro</option><option value="credit-card">Crédito</option><option value="debit-card">Débito</option>'}
function itemKey(item){return (item.itemKind||'product')+':'+item.productId}
function cartKey(item){return itemKey(item)+':'+JSON.stringify((item.componentSelections||[]).slice().sort((a,b)=>(a.choiceGroup+a.productId).localeCompare(b.choiceGroup+b.productId)))}
function catalogItem(key){return state.products.find(item=>itemKey(item)===key)}
function catalogCategory(product){if(product.itemKind==='combo')return 'Combos';if(product.kind==='drink')return 'Bebidas';if(product.kind==='food')return 'Comidas';return product.categoryLabel||'Produtos'}
function productMedia(product){if(product.imageDataUrl)return '<img class="product-photo" src="'+esc(product.imageDataUrl)+'" alt="">';return '<span class="product-mark" aria-hidden="true">'+esc(catalogCategory(product).slice(0,1))+'</span>'}
function ensureComboChoice(){if($('combo-choice'))return;document.body.insertAdjacentHTML('beforeend','<section class="overlay hidden" id="combo-choice"><div class="panel combo-choice-panel"><span class="panel-eyebrow">Monte o combo</span><h2 id="combo-choice-title"></h2><p class="subtle">Escolha os componentes que serão preparados. O estoque baixará exatamente estas unidades.</p><div id="combo-choice-list"></div><p class="notice" id="combo-choice-error"></p><button class="primary" id="combo-choice-confirm" type="button">Adicionar à venda</button><button class="link" id="combo-choice-cancel" type="button">Cancelar</button></div></section>')}
function drawServicePoints(){let target=$('sales-service-points');if(!target){document.querySelector('#sales .layout')?.insertAdjacentHTML('beforebegin','<section class="service-points" id="sales-service-points"></section>');target=$('sales-service-points')}if(!target)return false;const points=(state.context.servicePoints||[]).filter(point=>point.active);const selected=points.find(point=>point.id===state.servicePointId)||null;if(!selected){const tables=points.filter(point=>point.type==='table'),counters=points.filter(point=>point.type!=='table');const group=(title,items)=>items.length?'<section class="service-point-group"><h2>'+title+'</h2><div class="service-point-grid">'+items.map(point=>'<button class="service-point" data-service-point="'+esc(point.id)+'"><b>'+esc(point.label)+'</b><small>'+esc(point.type==='table'?'Entrar na mesa':'Entrar no balcão')+'</small></button>').join('')+'</div></section>':'';target.classList.add('service-points--entry');target.innerHTML='<div class="service-points__head"><span>Onde será o atendimento?</span><small>Escolha uma mesa ou balcão antes de iniciar uma venda.</small></div>'+group('Mesas',tables)+group('Balcões',counters)+(points.length?'':'<p class="empty">Cadastre ao menos uma mesa ou balcão no computador.</p>');target.querySelectorAll('[data-service-point]').forEach(button=>button.onclick=()=>{state.servicePointId=button.dataset.servicePoint;drawSales()});return false}target.classList.remove('service-points--entry');target.innerHTML='<div class="service-points__active"><div><span>'+esc(selected.type==='table'?'Mesa atual':'Balcão atual')+'</span><b>'+esc(selected.label)+'</b></div><button class="service-point-change" data-change-service-point="true">Trocar</button></div>';target.querySelector('[data-change-service-point]').onclick=()=>{if(state.cart.size>0&&!window.confirm('Trocar a mesa removerá os itens da venda atual. Continuar?'))return;state.cart.clear();state.servicePointId=null;drawSales()};return true}

function ensureOperationalViews(){
 if($('tickets'))return;
 $('app').insertAdjacentHTML('beforeend',
 '<section id="tickets" class="hidden mobile-operation"><div class="view-head"><div><span class="view-eyebrow">Bilheteria</span><h1>Ingressos</h1><p>Venda ou cortesia com código gerado pela central.</p></div></div><form id="ticket-form" class="mobile-form"><label class="field"><span>Lote</span><select id="ticket-lot" required></select></label><label class="field"><span>Responsável ou participante</span><input id="ticket-attendee" maxlength="120" required placeholder="Nome completo"></label><div class="split"><label class="field"><span>Origem</span><select id="ticket-source"><option value="door">Porta</option><option value="whatsapp">WhatsApp</option><option value="sympla">Sympla</option><option value="courtesy">Cortesia</option></select></label><label class="field"><span>Quantidade</span><input id="ticket-quantity" min="1" value="1" type="number" required></label></div><label class="field" id="ticket-payment-field"><span>Pagamento</span><select id="ticket-payment">'+paymentOptions()+'</select></label><button class="primary" id="ticket-submit">Registrar ingresso</button></form></section>'+
 '<section id="expenses" class="hidden mobile-operation"><div class="view-head"><div><span class="view-eyebrow">Financeiro</span><h1>Despesa</h1><p>Registre o compromisso; o pagamento continua controlado no PC.</p></div></div><form id="expense-form" class="mobile-form"><label class="field"><span>Categoria</span><input id="expense-category" maxlength="80" required placeholder="Ex.: Estrutura"></label><label class="field"><span>Descrição</span><input id="expense-description" maxlength="160" required placeholder="Ex.: Locação de gerador"></label><div class="split"><label class="field"><span>Valor</span><input id="expense-amount" inputmode="decimal" required placeholder="0,00"></label><label class="field"><span>Forma prevista</span><select id="expense-payment">'+paymentOptions()+'</select></label></div><label class="field"><span>Observação</span><input id="expense-note" maxlength="240" placeholder="Opcional"></label><button class="primary" id="expense-submit">Registrar despesa</button></form></section>'+
 '<section id="vouchers" class="hidden mobile-operation"><div class="view-head"><div><span class="view-eyebrow">Crédito</span><h1>Voucher</h1><p>Emita crédito vinculado a uma mesa ativa.</p></div></div><form id="voucher-form" class="mobile-form"><label class="field"><span>Mesa vinculada</span><select id="voucher-point" required></select></label><label class="field"><span>Identificação</span><input id="voucher-label" maxlength="100" required placeholder="Ex.: Crédito patrocinador"></label><div class="split"><label class="field"><span>Saldo inicial</span><input id="voucher-amount" inputmode="decimal" required placeholder="100,00"></label><label class="field"><span>Código opcional</span><input id="voucher-code" maxlength="32" placeholder="Gerado automaticamente"></label></div><button class="primary" id="voucher-submit">Emitir voucher</button></form></section>');
 $('ticket-form').onsubmit=submitTicket;
 $('ticket-source').onchange=drawTickets;
 $('expense-form').onsubmit=submitExpense;
 $('voucher-form').onsubmit=submitVoucher;
}

function tabs(){
 const list=[];
 if(enabled('sales'))list.push(['sales','Vendas']);
 if(enabled('inventory'))list.push(['inventory','Estoque']);
 if(enabled('tickets'))list.push(['tickets','Ingressos']);
 if(enabled('expenses'))list.push(['expenses','Despesas']);
 if(enabled('vouchers'))list.push(['vouchers','Vouchers']);
 if(!list.some(item=>item[0]===state.view))state.view=list[0]?.[0]||null;
 const html=list.map(item=>'<button class="tab '+(item[0]===state.view?'active':'')+'" data-view="'+item[0]+'"'+(item[0]===state.view?' aria-current="page"':'')+'>'+item[1]+'</button>').join('');
 [$('tabs'),$('tabs-desktop')].filter(Boolean).forEach(nav=>{nav.innerHTML=html;nav.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>{state.view=button.dataset.view;draw();button.scrollIntoView({block:'nearest',inline:'center'})})});
 const hasAccess=list.length>0;
 $('no-access')?.classList.toggle('hidden',hasAccess);
 ['sales','inventory','tickets','expenses','vouchers'].forEach(view=>$(view)?.classList.toggle('hidden',!hasAccess||state.view!==view));
 requestAnimationFrame(syncChromeHeight);
}

function drawSales(){
 if(!$('catalog'))return;
 const servicePointSelected=drawServicePoints();
 document.querySelector('#sales .layout')?.classList.toggle('hidden',!servicePointSelected);
 if(!servicePointSelected)return;
 const term=$('search').value.trim().toLowerCase();
 const products=state.products.filter(product=>product.visible!==false&&product.label.toLowerCase().includes(term));
 const sections=new Map();products.forEach(product=>{const category=catalogCategory(product);const group=sections.get(category)||[];group.push(product);sections.set(category,group)});const ordered=[...sections.keys()].sort((a,b)=>{const priority=['Combos','Bebidas','Comidas'];const left=priority.indexOf(a),right=priority.indexOf(b);return(left<0?99:left)-(right<0?99:right)||a.localeCompare(b,'pt-BR')});
 $('catalog').innerHTML=products.length?ordered.map(category=>'<section class="catalog-section"><div class="catalog-section__head"><h2>'+esc(category)+'</h2><span>'+sections.get(category).length+' itens</span></div><div class="catalog-grid">'+sections.get(category).map(product=>'<button class="product" data-item="'+esc(itemKey(product))+'" '+(product.quantity<1?'disabled':'')+'>'+productMedia(product)+'<span class="product-kind">'+esc(product.itemKind==='combo'?'Combo':product.kind==='food'?'Comida':'Bebida')+'</span><b>'+esc(product.label)+'</b><strong>'+money(product.unitPriceCents)+'</strong><small class="stock">'+product.quantity+' em estoque</small></button>').join('')+'</div></section>').join(''):'<p class="empty">Nenhum produto disponível.</p>';
 $('catalog').querySelectorAll('[data-item]').forEach(button=>button.onclick=()=>add(button.dataset.item));
 const lines=[...state.cart.values()];
 $('cart').innerHTML=lines.length?lines.map(item=>'<article class="line"><div><b>'+esc(item.label)+'</b><small>'+money(item.unitPriceCents)+' cada'+(item.componentSelections?.length?' · escolha registrada':'')+'</small></div><div class="quantity"><button aria-label="Diminuir quantidade" data-change="-1" data-item="'+esc(cartKey(item))+'">−</button><b>'+item.quantity+'</b><button aria-label="Aumentar quantidade" data-change="1" data-item="'+esc(cartKey(item))+'">+</button></div></article>').join(''):'<p class="empty">Toque em um produto para adicionar.</p>';
 $('cart').querySelectorAll('[data-change]').forEach(button=>button.onclick=()=>change(button.dataset.item,Number(button.dataset.change)));
 $('total').textContent=money(amount());$('cart-count').textContent=count()?count()+' itens':'Nenhum item';
 $('methods').querySelectorAll('button').forEach(button=>button.classList.toggle('active',button.dataset.method===state.method));
 $('charge').disabled=!state.online||!lines.length;$('charge').textContent=state.online?(lines.length?'Cobrar '+money(amount()):'Adicione produtos'):'Conexão necessária';
}
function drawStock(){const term=$('stock-search').value.trim().toLowerCase(),products=state.products.filter(product=>product.itemKind!=='combo'&&product.label.toLowerCase().includes(term));$('stock-list').innerHTML=products.length?products.map(product=>'<article class="stock-card"><b>'+esc(product.label)+'</b><span>'+esc(catalogCategory(product))+'</span><strong>'+product.quantity+' un.</strong><button data-move="'+esc(product.productId)+'" '+(!state.online?'disabled':'')+'>Movimentar</button></article>').join(''):'<p class="empty">Nenhum produto encontrado.</p>';$('stock-list').querySelectorAll('[data-move]').forEach(button=>button.onclick=()=>moveOpen(button.dataset.move))}
function drawTickets(){if(!$('ticket-lot'))return;const lots=(state.context.ticketLots||[]).filter(lot=>lot.active&&lot.availableQuantity>0);const current=$('ticket-lot').value;$('ticket-lot').innerHTML='<option value="">Selecione o lote</option>'+lots.map(lot=>'<option value="'+esc(lot.id)+'">'+esc(lot.name)+' · '+lot.availableQuantity+' disponíveis · '+money(lot.priceCents)+'</option>').join('');$('ticket-lot').value=lots.some(lot=>lot.id===current)?current:'';const courtesy=$('ticket-source').value==='courtesy';$('ticket-payment-field').classList.toggle('hidden',courtesy);$('ticket-payment').disabled=courtesy;$('ticket-submit').disabled=!state.online;$('ticket-submit').textContent=!state.online?'Conexão necessária':courtesy?'Registrar cortesia':'Registrar ingresso'}
function drawVouchers(){if(!$('voucher-point'))return;const points=(state.context.servicePoints||[]).filter(point=>point.active);const current=$('voucher-point').value;$('voucher-point').innerHTML='<option value="">Selecione a mesa</option>'+points.map(point=>'<option value="'+esc(point.id)+'">'+esc(point.label)+'</option>').join('');$('voucher-point').value=points.some(point=>point.id===current)?current:'';$('voucher-submit').disabled=!state.online;$('voucher-submit').textContent=state.online?'Emitir voucher':'Conexão necessária'}
function drawAvailability(){if($('expense-submit')){$('expense-submit').disabled=!state.online;$('expense-submit').textContent=state.online?'Registrar despesa':'Conexão necessária'}const movementSubmit=$('movement-form')?.querySelector('button[type="submit"],button:not([type])');if(movementSubmit)movementSubmit.disabled=!state.online}
function draw(){ensureOperationalViews();tabs();drawSales();drawStock();drawTickets();drawVouchers();drawAvailability()}
function choiceGroups(product){const groups=new Map();(product.components||[]).forEach(component=>{if(!component.choiceGroup)return;const group=groups.get(component.choiceGroup)||{id:component.choiceGroup,label:component.choiceLabel||'Escolha',quantity:component.quantity,options:[]};group.options.push(component);groups.set(component.choiceGroup,group)});return [...groups.values()]}
function cartCapacity(item){const product=catalogItem(itemKey(item));if(!product)return 0;const requirements=new Map();(product.components||[]).filter(component=>!component.choiceGroup).forEach(component=>requirements.set(component.productId,(requirements.get(component.productId)||0)+component.quantity));(item.componentSelections||[]).forEach(selection=>requirements.set(selection.productId,(requirements.get(selection.productId)||0)+selection.quantity));if(!requirements.size)return product.quantity;return Math.min(...[...requirements.entries()].map(([productId,quantity])=>Math.floor((state.products.find(product=>product.productId===productId)?.quantity||0)/quantity)))}
function addResolved(product,selections=[]){const item={...product,componentSelections:selections,quantity:0};const key=cartKey(item);const current=state.cart.get(key)||item;if(current.quantity>=cartCapacity(current))return;current.quantity++;state.cart.set(key,current);drawSales()}
function openComboChoice(product){state.pendingCombo=product;const groups=choiceGroups(product);$('combo-choice-title').textContent=product.label;$('combo-choice-list').innerHTML=groups.map(group=>'<section class="combo-choice-group" data-choice-group="'+esc(group.id)+'"><b>'+esc(group.label)+'</b><small>Escolha '+group.quantity+' unidade(s)</small>'+group.options.map(option=>'<label><span>'+esc(option.productId===product.productId?'':(state.products.find(product=>product.productId===option.productId)?.label||option.productId))+'</span><input type="number" min="0" max="'+(state.products.find(product=>product.productId===option.productId)?.quantity||0)+'" step="1" value="0" data-choice-option="'+esc(option.productId)+'"></label>').join('')+'</section>').join('');$('combo-choice-error').textContent='';$('combo-choice').classList.remove('hidden')}
function confirmComboChoice(){const product=state.pendingCombo;if(!product)return;const groups=choiceGroups(product),selections=[];for(const group of groups){const section=[...$('combo-choice-list').querySelectorAll('[data-choice-group]')].find(candidate=>candidate.dataset.choiceGroup===group.id);if(!section)return;const choices=[...section.querySelectorAll('[data-choice-option]')].map(input=>({choiceGroup:group.id,productId:input.dataset.choiceOption,quantity:Number(input.value)||0})).filter(choice=>choice.quantity>0);if(choices.reduce((sum,choice)=>sum+choice.quantity,0)!==group.quantity){$('combo-choice-error').textContent='Escolha exatamente '+group.quantity+' unidade(s) em '+group.label+'.';return}selections.push(...choices)}$('combo-choice').classList.add('hidden');state.pendingCombo=null;addResolved(product,selections)}
function add(key){const product=catalogItem(key);if(!product)return;if(choiceGroups(product).length){openComboChoice(product);return}addResolved(product)}
function change(key,delta){const item=state.cart.get(key);if(!item)return;if(delta>0&&item.quantity>=cartCapacity(item))return;item.quantity+=delta;if(item.quantity<1)state.cart.delete(key);else state.cart.set(key,item);drawSales()}
async function api(path,options={}){const response=await fetch(path,{credentials:'same-origin',...options});const body=await response.json().catch(()=>({}));if(response.status===401){logout('Sua sessão foi encerrada pela Produção.');throw new Error('Sua sessão foi encerrada.')}if(!response.ok)throw new Error(body.error?.message||'A central recusou a operação.');return body}
async function load(){const [catalog,context]=await Promise.all([api('/v1/mobile/catalog',{cache:'no-store'}),api('/v1/mobile/context',{cache:'no-store'})]);state.products=catalog.products||[];state.context=context||{ticketLots:[],servicePoints:[],voucherCodes:[]};online(true,'Conectado')}
function device(){let value=localStorage.getItem('gtrz-mobile-device');if(!value){value=uuid();localStorage.setItem('gtrz-mobile-device',value)}return value}
async function signIn(event){event.preventDefault();$('login-error').textContent='';try{await api('/v1/mobile/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:$('password').value,deviceId:device()})});$('password').value='';await start()}catch(error){$('login-error').textContent=error.message||'Não foi possível entrar.'}}
function reconnect(streamGeneration){if(streamGeneration!==state.streamGeneration||state.reconnectTimer!==null)return;state.reconnectTimer=setTimeout(()=>{state.reconnectTimer=null;if(streamGeneration===state.streamGeneration)streams()},1200)}
function connect(path,handler,streamGeneration){const generation=state.generation,socket=new WebSocket((location.protocol==='https:'?'wss':'ws')+'://'+location.host+path);socket.onmessage=event=>{if(generation!==state.generation||streamGeneration!==state.streamGeneration)return;try{handler(JSON.parse(event.data))}catch{}};socket.onerror=()=>socket.close();socket.onclose=()=>{if(generation!==state.generation||streamGeneration!==state.streamGeneration)return;online(false,'Reconectando');reconnect(streamGeneration)};return socket}
function streams(){clearTimeout(state.reconnectTimer);state.reconnectTimer=null;const streamGeneration=++state.streamGeneration;state.eventStream?.close();state.sessionStream?.close();state.eventStream=connect('/v1/mobile/stream',()=>void load(),streamGeneration);state.sessionStream=connect('/v1/mobile/session/stream',message=>{if(message.type==='mobile.session-revoked')logout('A Produção encerrou sua sessão.');if(message.type==='mobile.event-changed'){state.cart.clear();state.servicePointId=null;show('Evento alterado','O caixa foi atualizado para o evento selecionado na nuvem.',true);void load().then(streams)}if(message.type==='mobile.event-reset'){state.cart.clear();state.servicePointId=null;show('Evento zerado','Os dados operacionais deste evento foram removidos.',true);void load()}if(message.type==='mobile.permissions'&&message.operator){state.operator=message.operator;header();draw()}},streamGeneration)}
function header(){const active=Object.values(permissions()).filter(Boolean).length;$('operator').innerHTML='<b>'+esc(state.operator.name)+'</b>'+active+' '+(active===1?'módulo liberado':'módulos liberados');requestAnimationFrame(syncChromeHeight)}
async function start(){const session=await api('/v1/mobile/session');state.operator=session.operator;ensureOperationalViews();header();$('login').classList.add('hidden');$('app').classList.remove('hidden');await load();streams()}
function logout(message){state.generation++;state.streamGeneration++;clearTimeout(state.reconnectTimer);state.reconnectTimer=null;state.eventStream?.close();state.sessionStream?.close();state.operator=null;state.cart.clear();$('app').classList.add('hidden');$('login').classList.remove('hidden');$('login-error').textContent=message;online(false,'Senha necessária')}
async function charge(){if(!state.servicePointId)return;const items=[...state.cart.values()].map(item=>({productId:item.productId,itemKind:item.itemKind||'product',quantity:item.quantity,...(item.componentSelections?.length?{componentSelections:item.componentSelections.map(selection=>({...selection,quantity:selection.quantity*item.quantity}))}:{})})),sum=amount();$('charge').disabled=true;try{await api('/v1/mobile/sales',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({commandId:uuid(),saleId:uuid(),items,servicePointId:state.servicePointId,paymentMethod:state.method,receivedCents:state.method==='cash'?sum:null})});state.cart.clear();document.querySelector('details.cart')?.removeAttribute('open');show('Venda confirmada',money(sum)+' registrado e sincronizado.',true);await load()}catch(error){show('Venda não concluída',error.message||'Tente novamente.')}finally{drawSales()}}
function moveOpen(productId){if(!state.online)return;const product=state.products.find(item=>item.productId===productId);if(!product)return;$('movement-product').value=productId;$('movement-title').textContent='Movimentar '+product.label;$('movement-quantity').value='';$('movement-cost').value='';$('movement-note').value='';$('movement-type').value='purchase';toggleCost();$('movement').classList.remove('hidden')}
function updatePurchaseTotal(){const quantity=Number($('movement-quantity').value),total=Number($('movement-cost').value);$('purchase-total').textContent=Number.isFinite(quantity)&&quantity>0&&Number.isFinite(total)&&total>0?'Custo médio deste lote: '+money(Math.round(total*100/quantity))+' por unidade.':'Informe o total pago; o sistema calcula o custo médio.'}
function toggleCost(){const purchase=$('movement-type').value==='purchase';$('purchase-cost').classList.toggle('hidden',!purchase);$('movement-cost').required=purchase;updatePurchaseTotal()}
async function submitMove(event){event.preventDefault();if(!state.online)return;const type=$('movement-type').value,quantity=Number($('movement-quantity').value),cost=Number($('movement-cost').value);try{await api('/v1/mobile/stock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({commandId:uuid(),productId:$('movement-product').value,type,quantity,...(type==='purchase'?{purchaseTotalCents:Math.round(cost*100)}:{}),...($('movement-note').value.trim()?{note:$('movement-note').value.trim()}: {})})});$('movement').classList.add('hidden');show('Estoque atualizado','Movimento registrado e sincronizado.',true);await load()}catch(error){show('Movimento não concluído',error.message||'Confira os dados.')}}
async function submitTicket(event){event.preventDefault();if(!state.online)return;const source=$('ticket-source').value,quantity=Number($('ticket-quantity').value);try{await api('/v1/mobile/tickets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({commandId:uuid(),lotId:$('ticket-lot').value,attendeeName:$('ticket-attendee').value.trim(),source,quantity,...(source==='courtesy'?{}:{paymentMethod:$('ticket-payment').value})})});$('ticket-attendee').value='';$('ticket-quantity').value='1';show(source==='courtesy'?'Cortesia registrada':'Ingresso registrado','Operação sincronizada com a central.',true);await load()}catch(error){show('Ingresso não registrado',error.message||'Confira os dados.')}}
async function submitExpense(event){event.preventDefault();if(!state.online)return;try{await api('/v1/mobile/expenses',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({commandId:uuid(),category:$('expense-category').value.trim(),description:$('expense-description').value.trim(),amountCents:parseMoney($('expense-amount').value),paymentMethod:$('expense-payment').value,...($('expense-note').value.trim()?{note:$('expense-note').value.trim()}: {})})});$('expense-form').reset();show('Despesa registrada','Despesa registrada e sincronizada.',true);await load()}catch(error){show('Despesa não registrada',error.message||'Confira os dados.')}}
async function submitVoucher(event){event.preventDefault();if(!state.online)return;try{await api('/v1/mobile/vouchers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({commandId:uuid(),servicePointId:$('voucher-point').value,label:$('voucher-label').value.trim(),initialBalanceCents:parseMoney($('voucher-amount').value),...($('voucher-code').value.trim()?{code:$('voucher-code').value.trim()}: {})})});$('voucher-form').reset();show('Voucher emitido','Crédito registrado e vinculado à mesa.',true);await load()}catch(error){show('Voucher não emitido',error.message||'Confira os dados.')}}
function show(title,text,passive=false){clearTimeout(state.noticeTimer);$('result-title').textContent=title;$('result-text').textContent=text;$('result').classList.toggle('passive',passive);$('result').classList.remove('hidden');if(passive)state.noticeTimer=setTimeout(()=>{$('result').classList.add('hidden');$('result').classList.remove('passive')},1500)}
ensureComboChoice();$('login-form').onsubmit=signIn;$('search').oninput=drawSales;$('stock-search').oninput=drawStock;$('methods').onclick=event=>{if(event.target.dataset?.method){state.method=event.target.dataset.method;drawSales()}};$('charge').onclick=charge;$('movement-form').onsubmit=submitMove;$('movement-type').onchange=toggleCost;$('movement-quantity').oninput=updatePurchaseTotal;$('movement-cost').oninput=updatePurchaseTotal;$('movement-cancel').onclick=()=>$('movement').classList.add('hidden');$('combo-choice-cancel').onclick=()=>{$('combo-choice').classList.add('hidden');state.pendingCombo=null};$('combo-choice-confirm').onclick=confirmComboChoice;$('result-close').onclick=()=>{$('result').classList.add('hidden');$('result').classList.remove('passive')};window.addEventListener('resize',syncChromeHeight);window.visualViewport?.addEventListener('resize',syncChromeHeight);(async()=>{try{await start()}catch{logout('Informe sua senha para entrar.')}})();
`;
