export const cashierClientScript = String.raw`
const state={products:[],context:{ticketLots:[],servicePoints:[],voucherCodes:[]},cart:new Map(),method:'cash',online:false,operator:null,eventStream:null,sessionStream:null,generation:0,view:'sales'};
const $=id=>document.getElementById(id);
const money=c=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(c/100);
const uuid=()=>crypto.randomUUID();
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const permissions=()=>state.operator?.permissions||{sales:false,inventory:false,tickets:false,expenses:false,vouchers:false};
const enabled=key=>permissions()[key]===true;
function online(ok,text){state.online=ok;$('status').className='status '+(ok?'online':'');$('status').lastElementChild.textContent=text;drawSales()}
function amount(){return [...state.cart.values()].reduce((total,item)=>total+item.quantity*item.unitPriceCents,0)}
function count(){return [...state.cart.values()].reduce((total,item)=>total+item.quantity,0)}
function parseMoney(value){const amount=Number(String(value).trim().replace(',','.'));return Number.isFinite(amount)?Math.round(amount*100):0}
function paymentOptions(){return '<option value="pix">PIX</option><option value="cash">Dinheiro</option><option value="credit-card">Crédito</option><option value="debit-card">Débito</option>'}

function ensureOperationalViews(){
 if($('tickets'))return;
 $('app').insertAdjacentHTML('beforeend',
 '<section id="tickets" class="hidden mobile-operation"><div class="view-head"><div><span class="view-eyebrow">Bilheteria</span><h1>Ingressos</h1><p>Venda ou cortesia com código gerado pela central.</p></div></div><form id="ticket-form" class="mobile-form"><label class="field"><span>Lote</span><select id="ticket-lot" required></select></label><label class="field"><span>Responsável ou participante</span><input id="ticket-attendee" maxlength="120" required placeholder="Nome completo"></label><div class="split"><label class="field"><span>Origem</span><select id="ticket-source"><option value="door">Porta</option><option value="whatsapp">WhatsApp</option><option value="sympla">Sympla</option><option value="courtesy">Cortesia</option></select></label><label class="field"><span>Quantidade</span><input id="ticket-quantity" min="1" value="1" type="number" required></label></div><label class="field" id="ticket-payment-field"><span>Pagamento</span><select id="ticket-payment">'+paymentOptions()+'</select></label><button class="primary" id="ticket-submit">Registrar ingresso</button></form></section>'+
 '<section id="expenses" class="hidden mobile-operation"><div class="view-head"><div><span class="view-eyebrow">Financeiro</span><h1>Despesa</h1><p>Registre o compromisso; o pagamento continua controlado no PC.</p></div></div><form id="expense-form" class="mobile-form"><label class="field"><span>Categoria</span><input id="expense-category" maxlength="80" required placeholder="Ex.: Estrutura"></label><label class="field"><span>Descrição</span><input id="expense-description" maxlength="160" required placeholder="Ex.: Locação de gerador"></label><div class="split"><label class="field"><span>Valor</span><input id="expense-amount" inputmode="decimal" required placeholder="0,00"></label><label class="field"><span>Forma prevista</span><select id="expense-payment">'+paymentOptions()+'</select></label></div><label class="field"><span>Observação</span><input id="expense-note" maxlength="240" placeholder="Opcional"></label><button class="primary" id="expense-submit">Registrar despesa</button></form></section>'+
 '<section id="vouchers" class="hidden mobile-operation"><div class="view-head"><div><span class="view-eyebrow">Crédito</span><h1>Voucher</h1><p>Emita crédito vinculado a uma mesa ativa.</p></div></div><form id="voucher-form" class="mobile-form"><label class="field"><span>Mesa vinculada</span><select id="voucher-point" required></select></label><label class="field"><span>Identificação</span><input id="voucher-label" maxlength="100" required placeholder="Ex.: Crédito patrocinador"></label><div class="split"><label class="field"><span>Saldo inicial</span><input id="voucher-amount" inputmode="decimal" required placeholder="100,00"></label><label class="field"><span>Código opcional</span><input id="voucher-code" maxlength="32" placeholder="Gerado automaticamente"></label></div><button class="primary" id="voucher-submit">Emitir voucher</button></form></section>');
 $('ticket-form').onsubmit=submitTicket;
 $('ticket-source').onchange=drawTickets;
 $('expense-form').onsubmit=submitExpense;
 $('voucher-form').onsubmit=submitVoucher;
}

function tabs(){
 const list=[];
 if(enabled('sales'))list.push(['sales','Vendas']);
 if(enabled('inventory'))list.push(['inventory','Estoque']);
 if(enabled('tickets'))list.push(['tickets','Ingressos']);
 if(enabled('expenses'))list.push(['expenses','Despesas']);
 if(enabled('vouchers'))list.push(['vouchers','Vouchers']);
 if(!list.some(item=>item[0]===state.view))state.view=list[0]?.[0]||'sales';
 $('tabs').innerHTML=list.map(item=>'<button class="tab '+(item[0]===state.view?'active':'')+'" data-view="'+item[0]+'">'+item[1]+'</button>').join('');
 $('tabs').querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>{state.view=button.dataset.view;draw()});
 ['sales','inventory','tickets','expenses','vouchers'].forEach(view=>$(view)?.classList.toggle('hidden',state.view!==view));
}

function drawSales(){
 if(!$('catalog'))return;
 const term=$('search').value.trim().toLowerCase();
 const products=state.products.filter(product=>product.label.toLowerCase().includes(term));
 $('catalog').innerHTML=products.length?products.map(product=>'<button class="product" data-product="'+esc(product.productId)+'" '+(product.quantity<1?'disabled':'')+'><b>'+esc(product.label)+'</b><span>'+esc(product.kind||'Produto')+'</span><strong>'+money(product.unitPriceCents)+'</strong><small class="stock">'+product.quantity+' em estoque</small></button>').join(''):'<p class="empty">Nenhum produto disponível.</p>';
 $('catalog').querySelectorAll('[data-product]').forEach(button=>button.onclick=()=>add(button.dataset.product));
 const lines=[...state.cart.values()];
 $('cart').innerHTML=lines.length?lines.map(item=>'<article class="line"><div><b>'+esc(item.label)+'</b><small>'+money(item.unitPriceCents)+' cada</small></div><div class="quantity"><button data-change="-1" data-product="'+item.productId+'">−</button><b>'+item.quantity+'</b><button data-change="1" data-product="'+item.productId+'">+</button></div></article>').join(''):'<p class="empty">Toque em um produto para adicionar.</p>';
 $('cart').querySelectorAll('[data-change]').forEach(button=>button.onclick=()=>change(button.dataset.product,Number(button.dataset.change)));
 $('total').textContent=money(amount());$('cart-count').textContent=count()?count()+' itens':'Nenhum item';
 $('methods').querySelectorAll('button').forEach(button=>button.classList.toggle('active',button.dataset.method===state.method));
 $('charge').disabled=!state.online||!lines.length;$('charge').textContent=state.online?'Cobrar':'Conexão necessária';
}
function drawStock(){const term=$('stock-search').value.trim().toLowerCase(),products=state.products.filter(product=>product.label.toLowerCase().includes(term));$('stock-list').innerHTML=products.length?products.map(product=>'<article class="stock-card"><b>'+esc(product.label)+'</b><span>'+esc(product.kind||'Produto')+'</span><strong>'+product.quantity+' un.</strong><button data-move="'+esc(product.productId)+'">Movimentar</button></article>').join(''):'<p class="empty">Nenhum produto encontrado.</p>';$('stock-list').querySelectorAll('[data-move]').forEach(button=>button.onclick=()=>moveOpen(button.dataset.move))}
function drawTickets(){if(!$('ticket-lot'))return;const lots=(state.context.ticketLots||[]).filter(lot=>lot.active&&lot.availableQuantity>0);const current=$('ticket-lot').value;$('ticket-lot').innerHTML='<option value="">Selecione o lote</option>'+lots.map(lot=>'<option value="'+esc(lot.id)+'">'+esc(lot.name)+' · '+lot.availableQuantity+' disponíveis · '+money(lot.priceCents)+'</option>').join('');$('ticket-lot').value=lots.some(lot=>lot.id===current)?current:'';const courtesy=$('ticket-source').value==='courtesy';$('ticket-payment-field').classList.toggle('hidden',courtesy);$('ticket-payment').disabled=courtesy;$('ticket-submit').textContent=courtesy?'Registrar cortesia':'Registrar ingresso'}
function drawVouchers(){if(!$('voucher-point'))return;const points=(state.context.servicePoints||[]).filter(point=>point.active);const current=$('voucher-point').value;$('voucher-point').innerHTML='<option value="">Selecione a mesa</option>'+points.map(point=>'<option value="'+esc(point.id)+'">'+esc(point.label)+'</option>').join('');$('voucher-point').value=points.some(point=>point.id===current)?current:''}
function draw(){ensureOperationalViews();tabs();drawSales();drawStock();drawTickets();drawVouchers()}
function add(productId){const product=state.products.find(item=>item.productId===productId);if(!product)return;const item=state.cart.get(productId)||{...product,quantity:0};if(item.quantity>=product.quantity)return;item.quantity++;state.cart.set(productId,item);drawSales()}
function change(productId,delta){const item=state.cart.get(productId);if(!item)return;if(delta>0){const product=state.products.find(candidate=>candidate.productId===productId);if(!product||item.quantity>=product.quantity)return}item.quantity+=delta;if(item.quantity<1)state.cart.delete(productId);else state.cart.set(productId,item);drawSales()}
async function api(path,options={}){const response=await fetch(path,{credentials:'same-origin',...options});const body=await response.json().catch(()=>({}));if(response.status===401){logout('Sua sessão foi encerrada pela Produção.');throw new Error('Sua sessão foi encerrada.')}if(!response.ok)throw new Error(body.error?.message||'A central recusou a operação.');return body}
async function load(){const [catalog,context]=await Promise.all([api('/v1/mobile/catalog',{cache:'no-store'}),api('/v1/mobile/context',{cache:'no-store'})]);state.products=catalog.products||[];state.context=context||{ticketLots:[],servicePoints:[],voucherCodes:[]};online(true,'Conectado');draw()}
function device(){let value=localStorage.getItem('gtrz-mobile-device');if(!value){value=uuid();localStorage.setItem('gtrz-mobile-device',value)}return value}
async function signIn(event){event.preventDefault();$('login-error').textContent='';try{await api('/v1/mobile/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:$('password').value,deviceId:device()})});$('password').value='';await start()}catch(error){$('login-error').textContent=error.message||'Não foi possível entrar.'}}
function connect(path,handler){const generation=state.generation,socket=new WebSocket((location.protocol==='https:'?'wss':'ws')+'://'+location.host+path);socket.onmessage=event=>{if(generation!==state.generation)return;try{handler(JSON.parse(event.data))}catch{}};socket.onerror=()=>socket.close();socket.onclose=()=>{if(generation!==state.generation)return;online(false,'Reconectando');setTimeout(()=>{if(generation===state.generation)streams()},1200)};return socket}
function streams(){state.eventStream?.close();state.sessionStream?.close();state.eventStream=connect('/v1/mobile/stream',()=>void load());state.sessionStream=connect('/v1/mobile/session/stream',message=>{if(message.type==='mobile.session-revoked')logout('A Produção encerrou sua sessão.');if(message.type==='mobile.permissions'&&message.operator){state.operator=message.operator;header();draw()}})}
function header(){const active=Object.values(permissions()).filter(Boolean).length;$('operator').innerHTML='<b>'+esc(state.operator.name)+'</b>'+active+' permissão(ões) ativa(s)'}
async function start(){const session=await api('/v1/mobile/session');state.operator=session.operator;ensureOperationalViews();header();$('login').classList.add('hidden');$('app').classList.remove('hidden');await load();streams()}
function logout(message){state.generation++;state.eventStream?.close();state.sessionStream?.close();state.operator=null;state.cart.clear();$('app').classList.add('hidden');$('login').classList.remove('hidden');$('login-error').textContent=message;online(false,'Senha necessária')}
async function charge(){const items=[...state.cart.values()].map(item=>({productId:item.productId,quantity:item.quantity})),sum=amount();$('charge').disabled=true;try{await api('/v1/mobile/sales',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({commandId:uuid(),saleId:uuid(),items,paymentMethod:state.method,receivedCents:state.method==='cash'?sum:null})});state.cart.clear();show('Venda confirmada',money(sum)+' foi registrado em todos os computadores.');await load()}catch(error){show('Venda não concluída',error.message||'Tente novamente.')}finally{drawSales()}}
function moveOpen(productId){const product=state.products.find(item=>item.productId===productId);if(!product)return;$('movement-product').value=productId;$('movement-title').textContent='Movimentar '+product.label;$('movement-quantity').value='';$('movement-cost').value='';$('movement-note').value='';$('movement-type').value='purchase';toggleCost();$('movement').classList.remove('hidden')}
function updatePurchaseTotal(){const quantity=Number($('movement-quantity').value),total=Number($('movement-cost').value);$('purchase-total').textContent=Number.isFinite(quantity)&&quantity>0&&Number.isFinite(total)&&total>0?'Custo médio deste lote: '+money(Math.round(total*100/quantity))+' por unidade.':'Informe o total pago; o sistema calcula o custo médio.'}
function toggleCost(){const purchase=$('movement-type').value==='purchase';$('purchase-cost').classList.toggle('hidden',!purchase);$('movement-cost').required=purchase;updatePurchaseTotal()}
async function submitMove(event){event.preventDefault();const type=$('movement-type').value,quantity=Number($('movement-quantity').value),cost=Number($('movement-cost').value);try{await api('/v1/mobile/stock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({commandId:uuid(),productId:$('movement-product').value,type,quantity,...(type==='purchase'?{purchaseTotalCents:Math.round(cost*100)}:{}),...($('movement-note').value.trim()?{note:$('movement-note').value.trim()}: {})})});$('movement').classList.add('hidden');show('Estoque atualizado','O movimento foi registrado e sincronizado.');await load()}catch(error){show('Movimento não concluído',error.message||'Confira os dados.')}}
async function submitTicket(event){event.preventDefault();const source=$('ticket-source').value,quantity=Number($('ticket-quantity').value);try{await api('/v1/mobile/tickets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({commandId:uuid(),lotId:$('ticket-lot').value,attendeeName:$('ticket-attendee').value.trim(),source,quantity,...(source==='courtesy'?{}:{paymentMethod:$('ticket-payment').value})})});$('ticket-attendee').value='';$('ticket-quantity').value='1';show(source==='courtesy'?'Cortesia registrada':'Ingresso registrado','A central gerou o código e enviou a operação aos computadores.');await load()}catch(error){show('Ingresso não registrado',error.message||'Confira os dados.')}}
async function submitExpense(event){event.preventDefault();try{await api('/v1/mobile/expenses',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({commandId:uuid(),category:$('expense-category').value.trim(),description:$('expense-description').value.trim(),amountCents:parseMoney($('expense-amount').value),paymentMethod:$('expense-payment').value,...($('expense-note').value.trim()?{note:$('expense-note').value.trim()}: {})})});$('expense-form').reset();show('Despesa registrada','A despesa entrou no diário do evento e será refletida nos computadores.');await load()}catch(error){show('Despesa não registrada',error.message||'Confira os dados.')}}
async function submitVoucher(event){event.preventDefault();try{await api('/v1/mobile/vouchers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({commandId:uuid(),servicePointId:$('voucher-point').value,label:$('voucher-label').value.trim(),initialBalanceCents:parseMoney($('voucher-amount').value),...($('voucher-code').value.trim()?{code:$('voucher-code').value.trim()}: {})})});$('voucher-form').reset();show('Voucher emitido','O crédito foi registrado e vinculado à mesa escolhida.');await load()}catch(error){show('Voucher não emitido',error.message||'Confira os dados.')}}
function show(title,text){$('result-title').textContent=title;$('result-text').textContent=text;$('result').classList.remove('hidden')}
$('login-form').onsubmit=signIn;$('search').oninput=drawSales;$('stock-search').oninput=drawStock;$('methods').onclick=event=>{if(event.target.dataset?.method){state.method=event.target.dataset.method;drawSales()}};$('charge').onclick=charge;$('movement-form').onsubmit=submitMove;$('movement-type').onchange=toggleCost;$('movement-quantity').oninput=updatePurchaseTotal;$('movement-cost').oninput=updatePurchaseTotal;$('movement-cancel').onclick=()=>$('movement').classList.add('hidden');$('result-close').onclick=()=>$('result').classList.add('hidden');(async()=>{try{await start()}catch{logout('Informe sua senha para entrar.')}})();
`;
